export const products = [
  {
    id: 1,
    img: "/images/img1.webp",
    name: "Premium Wireless Headphones",
    price: "199.99",
    category: "electronics",
    rating: 4.5,
    reviews: 128,
    description:
      "High-quality sound with active noise cancellation, 30-hour battery life, and premium comfort for all-day use.",
    stock: 45,
    discount: 15,
  },
  {
    id: 2,
    img: "/images/img2.webp",
    name: "Elegant Minimalist Watch",
    price: "149.99",
    category: "accessories",
    rating: 4.8,
    reviews: 95,
    description:
      "Classic Swiss-inspired design with Japanese movement, water-resistant up to 50m, perfect for everyday wear.",
    stock: 32,
    discount: 10,
  },
  {
    id: 3,
    img: "/images/img3.webp",
    name: "Premium Leather Backpack",
    price: "189.99",
    category: "bags",
    rating: 4.7,
    reviews: 156,
    description:
      "Durable genuine leather construction with multiple compartments, ergonomic design, and lifetime warranty.",
    stock: 28,
    discount: 20,
  },
  {
    id: 4,
    img: "/images/img4.webp",
    name: "Designer Sunglasses",
    price: "129.99",
    category: "accessories",
    rating: 4.6,
    reviews: 87,
    description:
      "UV protection with polarized lenses, lightweight titanium frame, and anti-reflective coating.",
    stock: 51,
    discount: 12,
  },
  {
    id: 5,
    img: "/images/img5.webp",
    name: "Smart Watch Pro",
    price: "299.99",
    category: "electronics",
    rating: 4.9,
    reviews: 234,
    description:
      "Advanced fitness tracking, heart rate monitor, sleep analysis, and 7-day battery life with AMOLED display.",
    stock: 38,
    discount: 25,
  },
  {
    id: 6,
    img: "/images/img6.webp",
    name: "Canvas Messenger Bag",
    price: "99.99",
    category: "bags",
    rating: 4.4,
    reviews: 67,
    description:
      "Lightweight waxed canvas, weatherproof, adjustable shoulder strap, and perfect for daily commute.",
    stock: 72,
    discount: 8,
  },
  {
    id: 7,
    img: "/images/img7.webp",
    name: "Acoustic Guitar Studio",
    price: "349.99",
    category: "electronics",
    rating: 4.7,
    reviews: 112,
    description:
      "Solid spruce top, mahogany body, professional grade, includes carrying case and tuner.",
    stock: 15,
    discount: 18,
  },
  {
    id: 8,
    img: "/images/img8.webp",
    name: "Premium Ceramic Lamp",
    price: "285.00",
    category: "accessories",
    rating: 4.5,
    reviews: 78,
    description:
      "Hand-crafted ceramic base with linen shade, dimmable LED bulb, and modern aesthetic design.",
    stock: 24,
    discount: 22,
  },
  {
    id: 9,
    img: "/images/img9.webp",
    name: "Tech Nomad Pack",
    price: "399.99",
    category: "bags",
    rating: 4.8,
    reviews: 203,
    description:
      "Expandable capacity, TSA-approved, multiple charging ports, waterproof compartments, and laptop sleeve.",
    stock: 33,
    discount: 30,
  },
  {
    id: 10,
    img: "/images/img10.webp",
    name: "JBL Studio Speakers",
    price: "366.00",
    category: "electronics",
    rating: 4.6,
    reviews: 145,
    description:
      "Premium sound quality, 300W power output, Bluetooth 5.0, and premium build with oak finish.",
    stock: 19,
    discount: 16,
  },
  {
    id: 11,
    img: "/images/img11.webp",
    name: "Casual Cotton T-Shirt",
    price: "45.99",
    category: "clothes",
    rating: 4.3,
    reviews: 234,
    description:
      "100% organic cotton, comfortable fit, available in 10 colors, machine washable.",
    stock: 156,
    discount: 5,
  },
  {
    id: 12,
    img: "/images/img12.webp",
    name: "Premium Denim Jeans",
    price: "89.99",
    category: "clothes",
    rating: 4.6,
    reviews: 187,
    description:
      "Stretchable denim, perfect fit, fade-resistant, available in multiple styles and sizes.",
    stock: 98,
    discount: 12,
  },
  {
    id: 13,
    img: "/images/img13.webp",
    name: "Wireless Charging Pad",
    price: "59.99",
    category: "electronics",
    rating: 4.4,
    reviews: 156,
    description:
      "Fast charging for all Qi-enabled devices, non-slip surface, LED indicator, sleek design.",
    stock: 67,
    discount: 14,
  },
  {
    id: 14,
    img: "/images/img14.webp",
    name: "Stainless Steel Water Bottle",
    price: "34.99",
    category: "accessories",
    rating: 4.7,
    reviews: 421,
    description:
      "Double-walled insulated, keeps drinks cold 24hrs or hot 12hrs, eco-friendly, available in 8 colors.",
    stock: 143,
    discount: 10,
  },
  {
    id: 15,
    img: "/images/img15.webp",
    name: "Business Laptop Sleeve",
    price: "79.99",
    category: "bags",
    rating: 4.5,
    reviews: 98,
    description:
      "Neoprene material, protective padding, fits up to 16-inch laptops, stylish design.",
    stock: 55,
    discount: 15,
  },
  {
    id: 16,
    img: "/images/img16.webp",
    name: "Professional Camera Tripod",
    price: "129.99",
    category: "electronics",
    rating: 4.8,
    reviews: 167,
    description:
      "Aluminum alloy, adjustable height, ball head, maximum load 5kg, lightweight and portable.",
    stock: 41,
    discount: 18,
  },
];
